# 4.6.1
version: '3.1'
services:
  dashdot:
    image: mauricenino/dashdot
    container_name: Dashdot
    restart: unless-stopped
    ports:
      - 3001:3001
    privileged: true
    volumes:
      - /:/mnt/host:ro
    environment:
      - DASHDOT_SHOW_HOST=true
      - DASHDOT_ENABLE_CPU_TEMPS=true
      - DASHDOT_PAGE_TITLE=Expbox DashDot
      - DASHDOT_ALWAYS_SHOW_PERCENTAGES=true
      - DASHDOT_WIDGET_LIST=os,cpu,ram,network
      - DASHDOT_ACCEPT_OOKLA_EULA=true
      - DASHDOT_SPEED_TEST_INTERVAL=720
    env_file:
      - ../env/dashdot.env
