version: "3.1"
services:
  dashdot:
    image: mauricenino/dashdot:${DASHDOT_VERSION}
    container_name: Dashdot
    restart: unless-stopped
    ports:
      - ${PORT}:3001
    privileged: true
    volumes:
      - /:/mnt/host:ro
    environment:
      - DASHDOT_SHOW_HOST=true
      - DASHDOT_ACCEPT_OOKLA_EULA=true
      - DASHDOT_ENABLE_CPU_TEMPS=true
      - DASHDOT_ENABLE_STORAGE_SPLIT_VIEW=true
      - DASHDOT_ALWAYS_SHOW_PERCENTAGES=true
      - DASHDOT_PAGE_TITLE=Expbox Dash.
      - DASHDOT_WIDGET_LIST=os,cpu,ram,network
      - DASHDOT_SPEED_TEST_INTERVAL=720
    env_file:
      - .env.dashdot
      - ../.env.common


networks:
    default:
        external:
            name: ${DEFAULT_NETWORK}
    